"""Emit the addon quest database from the Wowhead Forever scrape.

Map ids come from Wowhead object pages (zone id plus Blizzard ui map id) and a
short list of area ids those pages never spawned in. This emitter does not
read All The Things.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

# Wowhead quest pages use classic area ids. Object pages already pair those
# ids with a ui map. These are the area ids that have quest starts but no
# object spawn in the scrape, named from the quest page and matched to the
# Blizzard ui map for that zone.
STATIC_ZONE_UI_MAP: dict[int, int] = {
    4: 1419,  # Blasted Lands
    493: 1450,  # Moonglade
    1638: 1456,  # Thunder Bluff
    1657: 1457,  # Darnassus
    2597: 1459,  # Alterac Valley
}

PROFESSION_SKILL: dict[str, int] = {
    "alchemy": 171,
    "blacksmithing": 164,
    "cooking": 185,
    "enchanting": 333,
    "engineering": 202,
    "first aid": 129,
    "first-aid": 129,
    "fishing": 356,
    "herbalism": 182,
    "leatherworking": 165,
    "mining": 186,
    "skinning": 393,
    "tailoring": 197,
}

_CAMPING_NAME = re.compile(r"^Camping 101:\s*(.+)$", re.IGNORECASE)
_NPC_TYPE = 1


def emit_database(data_root: Path) -> tuple[dict[int, dict[str, Any]], dict[str, Any]]:
    index = _load_json(data_root / "quest_index.json")
    zone_ui = _zone_ui_map(data_root / "object")
    quests: dict[int, dict[str, Any]] = {}
    skipped_no_coords = 0
    unmapped: dict[str, int] = {}

    details = data_root / "details"
    for path in sorted(details.glob("*.json"), key=lambda item: int(item.stem) if item.stem.isdigit() else 0):
        if not path.stem.isdigit():
            continue
        detail = _load_json(path)
        quest_id = int(detail.get("questId") or path.stem)
        entry = index.get(str(quest_id), {})
        coords, npc_ids, missed_zones = _start_coords(detail, zone_ui)
        for zone_id in missed_zones:
            key = str(zone_id)
            unmapped[key] = unmapped.get(key, 0) + 1
        if not coords:
            skipped_no_coords += 1
            continue
        quests[quest_id] = _record(quest_id, detail, entry, coords, npc_ids)

    stats = _stats(quests, skipped_no_coords, unmapped)
    return quests, stats


def emit_lua_database(quests: dict[int, dict[str, Any]]) -> str:
    lines = [
        "-- AUTO-GENERATED FILE",
        "-- DO NOT EDIT MANUALLY",
        "-- Source: Wowhead Forever (data/forever-quests)",
        "-- Generated by tools/emit_wowhead_db.py",
        "--",
        "-- Compact quest-start records keyed by questID. Coordinates are Wowhead",
        "-- 0-100 positions on Blizzard UiMapIDs.",
        "",
        "local ADDON_NAME, ns = ...",
        "ns.Quests = {",
    ]
    for quest_id in sorted(quests):
        lines.append(f"\t[{quest_id}] = {{ {_quest_body(quests[quest_id])} }},")
    lines.append("}")
    lines.append("")
    lines.append("ns.ByMap = {")
    for map_id, ids in _index_by_map(quests).items():
        inner = ", ".join(str(quest_id) for quest_id in ids)
        lines.append(f"\t[{map_id}] = {{ {inner} }},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def emit_metadata(stats: dict[str, Any]) -> str:
    lines = [
        "-- AUTO-GENERATED FILE",
        "-- DO NOT EDIT MANUALLY",
        "-- Source: Wowhead Forever (data/forever-quests)",
        "-- Generated by tools/emit_wowhead_db.py",
        "",
        "local ADDON_NAME, ns = ...",
        "ns.Metadata = {",
        '\tsource = "wowhead-forever",',
        f"\tquestCount = {int(stats['quests_emitted'])},",
        f"\tcoordCount = {int(stats['coord_pins'])},",
        f"\tattunementCount = {int(stats['attunement_quests'])},",
        f"\tmapCount = {int(stats['map_count'])},",
        '\tgeneratedBy = "tools/emit_wowhead_db.py",',
        "}",
        "",
    ]
    return "\n".join(lines)


def write_outputs(out_dir: Path, quests: dict[int, dict[str, Any]], stats: dict[str, Any]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "ForeverQuests.lua").write_text(emit_lua_database(quests), encoding="utf-8", newline="\n")
    (out_dir / "Metadata.lua").write_text(emit_metadata(stats), encoding="utf-8", newline="\n")
    (out_dir / "build_report.json").write_text(
        json.dumps(stats, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def _record(
    quest_id: int,
    detail: dict[str, Any],
    entry: dict[str, Any],
    coords: list[tuple[float, float, int]],
    npc_ids: list[int],
) -> dict[str, Any]:
    category = detail.get("pinCategory") or entry.get("pinCategory") or "normal"
    kinds = set(entry.get("sourceKinds") or [])
    record: dict[str, Any] = {
        "quest_id": quest_id,
        "coords": coords,
        "npcs": npc_ids,
        "faction": detail.get("faction") or entry.get("faction"),
        "races": [int(race) for race in detail.get("races") or entry.get("races") or []],
        "classes": [int(class_id) for class_id in detail.get("classes") or entry.get("classes") or []],
        "min_level": detail.get("minLevel") if detail.get("minLevel") is not None else entry.get("minLevel"),
        "repeatable": category == "repeatable",
        "is_yearly": "world_event" in kinds,
        "is_attunement": category == "attunement",
        "is_instance_quest": category in {"instance", "raid"},
        "is_pvp": category == "pvp",
        "require_skill": _require_skill(entry),
    }
    return record


def _require_skill(entry: dict[str, Any]) -> int | None:
    slugs = []
    for slug in entry.get("sourceSlugs") or []:
        if isinstance(slug, str) and slug.startswith("profession/"):
            slugs.append(slug.split("/", 1)[1])
    skills = {PROFESSION_SKILL[slug] for slug in slugs if slug in PROFESSION_SKILL}
    name = entry.get("name") or ""
    camping = _CAMPING_NAME.match(name)
    if camping:
        skill = PROFESSION_SKILL.get(camping.group(1).strip().lower())
        if skill is not None:
            skills.add(skill)
    if len(skills) == 1:
        return next(iter(skills))
    return None


def _start_coords(
    detail: dict[str, Any],
    zone_ui: dict[int, int],
) -> tuple[list[tuple[float, float, int]], list[int], list[int]]:
    coords: list[tuple[float, float, int]] = []
    seen: set[tuple[int, float, float]] = set()
    npc_ids: list[int] = []
    seen_npcs: set[int] = set()
    missed: list[int] = []

    def add(zone_id: Any, ui_map: Any, x_value: Any, y_value: Any) -> None:
        point = _point(zone_id, ui_map, x_value, y_value, zone_ui)
        if point is None:
            if _looks_like_coord(x_value, y_value) and not isinstance(ui_map, int):
                try:
                    missed.append(int(zone_id))
                except (TypeError, ValueError):
                    missed.append(-1)
            return
        key = (point[2], round(point[0], 2), round(point[1], 2))
        if key in seen:
            return
        seen.add(key)
        coords.append(point)

    mapper = detail.get("mapper") or {}
    for zone_id, block in (mapper.get("objectives") or {}).items():
        if not isinstance(block, dict):
            continue
        for level in block.get("levels") or []:
            if not isinstance(level, list):
                continue
            for entry in level:
                if not isinstance(entry, dict) or entry.get("point") != "start":
                    continue
                # NPC pages list every known spawn in `coords` (one courier has
                # hundreds). The single `coord` is the pin Wowhead highlights.
                # Objects keep every spawn.
                if entry.get("type") == _NPC_TYPE:
                    for x_value, y_value in _primary_coordinate(entry):
                        add(zone_id, None, x_value, y_value)
                    if isinstance(entry.get("id"), int):
                        npc_id = int(entry["id"])
                        if npc_id not in seen_npcs:
                            seen_npcs.add(npc_id)
                            npc_ids.append(npc_id)
                else:
                    for x_value, y_value in _entry_coordinates(entry):
                        add(zone_id, None, x_value, y_value)

    for pin in list(detail.get("objectSpawns") or []) + list(detail.get("startPins") or []):
        if not isinstance(pin, dict):
            continue
        add(pin.get("zoneId"), pin.get("uiMapId"), pin.get("x"), pin.get("y"))

    coords.sort(key=lambda item: (item[2], item[0], item[1]))
    return coords, npc_ids, missed


def _point(
    zone_id: Any,
    ui_map: Any,
    x_value: Any,
    y_value: Any,
    zone_ui: dict[int, int],
) -> tuple[float, float, int] | None:
    if not _looks_like_coord(x_value, y_value):
        return None
    x_coord = float(x_value)
    y_coord = float(y_value)
    if x_coord == 0 and y_coord == 0:
        return None
    map_id = ui_map if isinstance(ui_map, int) else None
    if map_id is None:
        try:
            map_id = zone_ui.get(int(zone_id))
        except (TypeError, ValueError):
            map_id = None
    if map_id is None:
        return None
    return (x_coord, y_coord, int(map_id))


def _looks_like_coord(x_value: Any, y_value: Any) -> bool:
    return isinstance(x_value, (int, float)) and isinstance(y_value, (int, float)) and not isinstance(x_value, bool)


def _primary_coordinate(entry: dict[str, Any]) -> list[tuple[float, float]]:
    coord = entry.get("coord")
    if isinstance(coord, list) and len(coord) == 2 and _looks_like_coord(coord[0], coord[1]):
        return [(float(coord[0]), float(coord[1]))]
    pairs = _entry_coordinates(entry)
    return pairs[:1]


def _entry_coordinates(entry: dict[str, Any]) -> list[tuple[float, float]]:
    pairs: list[tuple[float, float]] = []
    coords = entry.get("coords")
    if isinstance(coords, list):
        for pair in coords:
            if isinstance(pair, list) and len(pair) == 2 and _looks_like_coord(pair[0], pair[1]):
                pairs.append((float(pair[0]), float(pair[1])))
    if pairs:
        return pairs
    coord = entry.get("coord")
    if isinstance(coord, list) and len(coord) == 2 and _looks_like_coord(coord[0], coord[1]):
        return [(float(coord[0]), float(coord[1]))]
    return []


def _zone_ui_map(object_dir: Path) -> dict[int, int]:
    votes: dict[int, dict[int, int]] = {}
    if object_dir.is_dir():
        for path in object_dir.glob("*.json"):
            record = _load_json(path)
            for spawn in record.get("spawns") or []:
                zone_id = spawn.get("zoneId")
                ui_map = spawn.get("uiMapId")
                if not isinstance(zone_id, int) or not isinstance(ui_map, int):
                    continue
                bucket = votes.setdefault(zone_id, {})
                bucket[ui_map] = bucket.get(ui_map, 0) + 1
    resolved = dict(STATIC_ZONE_UI_MAP)
    for zone_id, counts in votes.items():
        ui_map = max(counts, key=lambda key: (counts[key], -key))
        resolved[zone_id] = ui_map
    return resolved


def _stats(quests: dict[int, dict[str, Any]], skipped_no_coords: int, unmapped: dict[str, int]) -> dict[str, Any]:
    maps: set[int] = set()
    coord_pins = 0
    attunement = repeatable = pvp = instance = seasonal = 0
    for record in quests.values():
        coord_pins += len(record["coords"])
        for _x, _y, map_id in record["coords"]:
            maps.add(map_id)
        if record["is_attunement"]:
            attunement += 1
        if record["repeatable"]:
            repeatable += 1
        if record["is_pvp"]:
            pvp += 1
        if record["is_instance_quest"]:
            instance += 1
        if record["is_yearly"]:
            seasonal += 1
    return {
        "attunement_quests": attunement,
        "coord_pins": coord_pins,
        "generated_by": "tools/emit_wowhead_db.py",
        "instance_quests": instance,
        "map_count": len(maps),
        "map_ids": sorted(maps),
        "pvp_quests": pvp,
        "quests_emitted": len(quests),
        "repeatable_quests": repeatable,
        "seasonal_quests": seasonal,
        "skipped_no_coords": skipped_no_coords,
        "source": "wowhead-forever",
        "unmapped_zone_pins": unmapped,
    }


def _index_by_map(quests: dict[int, dict[str, Any]]) -> dict[int, list[int]]:
    by_map: dict[int, list[int]] = {}
    for quest_id in sorted(quests):
        seen: set[int] = set()
        for _x, _y, map_id in quests[quest_id]["coords"]:
            if map_id in seen:
                continue
            seen.add(map_id)
            by_map.setdefault(map_id, []).append(quest_id)
    return dict(sorted(by_map.items()))


def _quest_body(record: dict[str, Any]) -> str:
    x_coord, y_coord, map_id = record["coords"][0]
    parts = [f"mapID={map_id}", f"x={_num(x_coord)}", f"y={_num(y_coord)}"]
    if len(record["coords"]) > 1:
        rendered = ", ".join(
            f"{{ {_num(x_value)}, {_num(y_value)}, {coord_map} }}"
            for x_value, y_value, coord_map in record["coords"]
        )
        parts.append(f"coords={{ {rendered} }}")
    npcs: list[int] = record["npcs"]
    if len(npcs) == 1:
        parts.append(f"qg={npcs[0]}")
    elif npcs:
        parts.append("qgs=" + _lua_int_list(npcs))
    faction = record.get("faction")
    if faction:
        parts.append(f'faction="{faction}"')
    if record["races"]:
        parts.append("races=" + _lua_int_list(record["races"]))
    if record["classes"]:
        parts.append("classes=" + _lua_int_list(record["classes"]))
    if record.get("require_skill") is not None:
        parts.append(f"requireSkill={int(record['require_skill'])}")
    if record.get("min_level") is not None:
        parts.append(f"minLevel={int(record['min_level'])}")
    if record["repeatable"]:
        parts.append("repeatable=true")
    if record["is_yearly"]:
        parts.append("isYearly=true")
    if record["is_attunement"]:
        parts.append("isAttunement=true")
    if record["is_instance_quest"]:
        parts.append("isInstanceQuest=true")
    if record["is_pvp"]:
        parts.append("isPvP=true")
    return ", ".join(parts)


def _lua_int_list(values: list[int]) -> str:
    return "{ " + ", ".join(str(int(value)) for value in values) + " }"


def _num(value: float) -> str:
    if float(value).is_integer():
        return str(int(value))
    return f"{value:.4f}".rstrip("0").rstrip(".")


def _load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        return {}
    return payload
