#!/usr/bin/env python3
"""Validate committed generated database files."""

from __future__ import annotations

import json
import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "Database"


def _read(name: str) -> str:
    return (DB / name).read_text(encoding="utf-8")


class GeneratedDatabaseTests(unittest.TestCase):
    def test_headers_and_metadata(self) -> None:
        quests = _read("ForeverQuests.lua")
        meta = _read("Metadata.lua")
        for text in (quests, meta):
            self.assertIn("-- AUTO-GENERATED FILE", text)
            self.assertIn("-- DO NOT EDIT MANUALLY", text)
            self.assertIn("-- Source: Questie/QuestieDB", text)
            self.assertIn("-- Generated by cmd/compile", text)
            self.assertNotIn("attCommit", text)
            self.assertNotIn("AllTheThings", text)
            self.assertNotIn("generatedAt", text)
        self.assertNotIn("questieCommit", quests)
        questie = re.search(r'questieCommit = "([0-9a-f]{7,})"', meta)
        database = re.search(r'databaseCommit = "([0-9a-f]{7,})"', meta)
        self.assertIsNotNone(questie)
        self.assertIsNotNone(database)
        self.assertIn("ns.Quests = {", quests)
        self.assertIn("ns.ByMap = {", quests)

    def test_report_matches_lua_counts(self) -> None:
        report = json.loads((DB / "build_report.json").read_text(encoding="utf-8"))
        quests_text = _read("ForeverQuests.lua")
        meta = _read("Metadata.lua")
        quest_ids = set(int(x) for x in re.findall(r"\[(\d+)\] = \{", quests_text.split("ns.ByMap")[0]))
        self.assertEqual(len(quest_ids), int(report["quests_emitted"]))
        self.assertIn(report["questie_commit"], meta)
        self.assertIn(report["database_commit"], meta)
        self.assertNotIn("att_sha", report)
        self.assertNotIn("generatedAt", report)
        self.assertNotIn("isAttunement=true", quests_text)
        quests_part = quests_text.split("ns.ByMap")[0]
        coord_pins = 0
        for line in quests_part.splitlines():
            if "coords={" in line:
                tail = line.split("coords={", 1)[1]
                stop = len(tail)
                for marker in (
                    ", qg=",
                    ", qgs=",
                    ", turnIns=",
                    ", sourceQuests=",
                    ", altQuests=",
                    ", faction=",
                    ", races=",
                    ", classes=",
                    ", requireSkill=",
                    ", minLevel=",
                    ", is",
                ):
                    index = tail.find(marker)
                    if index != -1:
                        stop = min(stop, index)
                coord_pins += len(re.findall(r"\{ [0-9.]+, [0-9.]+, \d+ \}", tail[:stop]))
            elif "mapID=" in line:
                coord_pins += 1
        self.assertEqual(coord_pins, int(report["coord_pins"]))
        self.assertIn(f"coordCount = {coord_pins}", meta)
        self.assertIn(f"mapCount = {int(report['map_count'])}", meta)

    def test_bymap_ids_exist_and_have_coordinates(self) -> None:
        text = _read("ForeverQuests.lua")
        quests_part, bymap_part = text.split("ns.ByMap = {", 1)
        quest_ids = set(int(x) for x in re.findall(r"\[(\d+)\] = \{", quests_part))
        for match in re.finditer(r"\[(\d+)\] = \{([^}]*)\}", bymap_part):
            ids = [int(x) for x in re.findall(r"\d+", match.group(2))]
            for quest_id in ids:
                self.assertIn(quest_id, quest_ids)
                self.assertRegex(quests_part, rf"\[{quest_id}\] = \{{ mapID=\d+, x=\d")

    def test_translated_start_and_quest_flags(self) -> None:
        text = _read("ForeverQuests.lua")
        self.assertRegex(text, r"\[123\] = \{ mapID=1429, x=25\.02, y=92\.9")
        self.assertRegex(text, r"\[8673\] = \{[^\n]*isYearly=true")
        self.assertNotRegex(text, r"\[155\] = \{[^\n]*isYearly=true")
        self.assertRegex(text, r"\[813\] = \{[^\n]*repeatable=true")
        self.assertRegex(text, r"\[90\] = \{[^\n]*requireSkill=185")

    def test_docs_credit_questie_not_att(self) -> None:
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        attribution = (ROOT / "ATTRIBUTION.md").read_text(encoding="utf-8")
        for text in (readme, attribution):
            self.assertNotIn("All The Things", text)
            self.assertNotIn("AllTheThings", text)
        self.assertIn("Questie", readme)
        self.assertIn("wow-database", readme)
        self.assertIn("QuestieDB", attribution)


if __name__ == "__main__":
    if not (DB / "ForeverQuests.lua").is_file():
        print("Database/ForeverQuests.lua is missing; generate it first.", file=sys.stderr)
        raise SystemExit(1)
    unittest.main()
