#!/usr/bin/env python3
"""Validate committed generated database files."""

from __future__ import annotations

import json
import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "Database"


def _read(name: str) -> str:
    return (DB / name).read_text(encoding="utf-8")


class GeneratedDatabaseTests(unittest.TestCase):
    def test_headers_and_metadata(self) -> None:
        quests = _read("ForeverQuests.lua")
        meta = _read("Metadata.lua")
        for text in (quests, meta):
            self.assertIn("-- AUTO-GENERATED FILE", text)
            self.assertIn("-- DO NOT EDIT MANUALLY", text)
            self.assertIn("-- Source: ATTWoWAddon/AllTheThings", text)
            self.assertIn("-- Generated by tools/build_quest_db.py", text)
        sha = re.search(r'attCommit = "([0-9a-f]{7,})"', meta)
        self.assertIsNotNone(sha)
        self.assertIn(f"-- ATT commit: {sha.group(1)}", quests)
        self.assertIn("ns.Quests = {", quests)
        self.assertIn("ns.ByMap = {", quests)
        self.assertNotEqual(sha.group(1), "")

    def test_report_matches_lua_counts(self) -> None:
        report = json.loads((DB / "build_report.json").read_text(encoding="utf-8"))
        quests_text = _read("ForeverQuests.lua")
        meta = _read("Metadata.lua")
        quest_ids = set(int(x) for x in re.findall(r"\[(\d+)\] = \{", quests_text.split("ns.ByMap")[0]))
        self.assertGreater(len(quest_ids), 0)
        self.assertEqual(len(quest_ids), int(report["quests_emitted"]))
        self.assertIn(report["att_sha"], meta)
        self.assertEqual(report["parse_errors"], [])
        attunement_count = len(re.findall(r"isAttunement=true", quests_text))
        self.assertEqual(attunement_count, int(report["attunement_quests"]))
        self.assertIn(f"attunementCount = {attunement_count}", meta)

    def test_bymap_ids_exist_and_have_coordinates(self) -> None:
        text = _read("ForeverQuests.lua")
        quests_part, bymap_part = text.split("ns.ByMap = {", 1)
        quest_ids = set(int(x) for x in re.findall(r"\[(\d+)\] = \{", quests_part))
        for match in re.finditer(r"\[(\d+)\] = \{([^}]*)\}", bymap_part):
            ids = [int(x) for x in re.findall(r"\d+", match.group(2))]
            for quest_id in ids:
                self.assertIn(quest_id, quest_ids)
        for quest_id in list(quest_ids)[:50]:
            self.assertRegex(
                quests_part,
                rf"\[{quest_id}\] = \{{ mapID=\d+, x=-?\d",
            )

    def test_mulgore_zone_quest_and_holiday_flag(self) -> None:
        text = _read("ForeverQuests.lua")
        self.assertRegex(
            text,
            r"\[754\] = \{ mapID=1412, x=48\.5, y=60\.4",
        )
        self.assertRegex(
            text,
            r"\[8673\] = \{[^}]*isYearly=true",
        )
        self.assertRegex(
            text,
            r"\[813\] = \{[^}]*repeatable=true",
        )

    def test_known_attunement_chains_are_flagged(self) -> None:
        text = _read("ForeverQuests.lua")
        for quest_id in (5505, 5511, 6502, 6602, 7761, 7848, 9121, 9122, 9123):
            self.assertRegex(text, rf"\[{quest_id}\] = \{{[^\n]*isAttunement=true")


if __name__ == "__main__":
    if not (DB / "ForeverQuests.lua").is_file():
        print("Database/ForeverQuests.lua is missing; generate it first.", file=sys.stderr)
        raise SystemExit(1)
    unittest.main()
