-- AUTO-GENERATED FILE
-- DO NOT EDIT MANUALLY
-- Source: ATTWoWAddon/AllTheThings
-- ATT commit: 19896d7fddbd815e034872fb14729684076348be
-- Generated by tools/build_quest_db.py

local ADDON_NAME, ns = ...
ns.Metadata = {
	source = "ATTWoWAddon/AllTheThings",
	attCommit = "19896d7fddbd815e034872fb14729684076348be",
	attRef = "https://github.com/ATTWoWAddon/AllTheThings.git",
	questCount = 3967,
	coordCount = 4230,
	attunementCount = 27,
	filesParsed = 146,
	generatedBy = "tools/build_quest_db.py",
}
