-- AUTO-GENERATED FILE
-- DO NOT EDIT MANUALLY
-- Source: ATTWoWAddon/AllTheThings
-- ATT commit: 37c4c06a6e9978c3698c4c93fce38090c58f9163
-- Generated by tools/build_quest_db.py

local ADDON_NAME, ns = ...
ns.Metadata = {
	source = "ATTWoWAddon/AllTheThings",
	attCommit = "37c4c06a6e9978c3698c4c93fce38090c58f9163",
	attRef = "https://github.com/ATTWoWAddon/AllTheThings.git",
	questCount = 3980,
	coordCount = 4243,
	attunementCount = 27,
	filesParsed = 145,
	generatedBy = "tools/build_quest_db.py",
}
