-- AUTO-GENERATED FILE
-- DO NOT EDIT MANUALLY
-- Source: wow-database
-- Generated by cmd/compile

local ADDON_NAME, ns = ...
ns.Metadata = {
	source = "wow-database",
	databaseCommit = "ca1df11d8769bf41cd52de01ed6ade6707890b71",
	questCount = 5010,
	coordCount = 2751,
	mapCount = 40,
	generatedBy = "cmd/compile",
}
