"""Deterministic Lua / JSON emitters for generated Forever Quest Pins data."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

from .extract import QuestRecord


HEADER_LINES = (
    "-- AUTO-GENERATED FILE",
    "-- DO NOT EDIT MANUALLY",
    "-- Source: ATTWoWAddon/AllTheThings",
)


def emit_lua_database(
    quests: dict[int, QuestRecord],
    att_sha: str,
    generated_by: str = "tools/build_quest_db.py",
) -> str:
    lines = [
        *HEADER_LINES,
        f"-- ATT commit: {att_sha}",
        f"-- Generated by {generated_by}",
        "--",
        "-- Compact quest-start records keyed by questID. Coordinates use ATT's",
        "-- 0-100 UiMapID space (the same system as Blizzard world-map pins).",
        "",
        "local ADDON_NAME, ns = ...",
        "ns.Quests = {",
    ]
    for quest_id in sorted(quests):
        record = quests[quest_id]
        body = _quest_body(record)
        lines.append(f"\t[{quest_id}] = {{ {body} }},")
    lines.append("}")
    lines.append("")
    lines.append("ns.ByMap = {")
    by_map = _index_by_map(quests)
    for map_id in sorted(by_map):
        ids = ", ".join(str(qid) for qid in by_map[map_id])
        lines.append(f"\t[{map_id}] = {{ {ids} }},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def emit_metadata(
    att_sha: str,
    att_ref: str,
    stats: dict[str, Any],
    generated_by: str = "tools/build_quest_db.py",
) -> str:
    lines = [
        *HEADER_LINES,
        f"-- ATT commit: {att_sha}",
        f"-- Generated by {generated_by}",
        "",
        "local ADDON_NAME, ns = ...",
        "ns.Metadata = {",
        f'\tsource = "ATTWoWAddon/AllTheThings",',
        f'\tattCommit = "{att_sha}",',
        f'\tattRef = "{_escape(att_ref)}",',
        f"\tquestCount = {int(stats.get('quests_emitted', 0))},",
        f"\tcoordCount = {int(stats.get('coord_pins', 0))},",
        f"\tattunementCount = {int(stats.get('attunement_quests', 0))},",
        f"\tfilesParsed = {int(stats.get('files_parsed', 0))},",
        f"\tgeneratedBy = \"{generated_by}\",",
        "}",
        "",
    ]
    return "\n".join(lines)


def emit_report(stats: dict[str, Any]) -> str:
    return json.dumps(stats, indent=2, sort_keys=True) + "\n"


def write_outputs(
    out_dir: Path,
    quests: dict[int, QuestRecord],
    att_sha: str,
    att_ref: str,
    stats: dict[str, Any],
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "ForeverQuests.lua").write_text(
        emit_lua_database(quests, att_sha),
        encoding="utf-8",
        newline="\n",
    )
    (out_dir / "Metadata.lua").write_text(
        emit_metadata(att_sha, att_ref, stats),
        encoding="utf-8",
        newline="\n",
    )
    (out_dir / "build_report.json").write_text(emit_report(stats), encoding="utf-8", newline="\n")


def _quest_body(record: QuestRecord) -> str:
    parts: list[str] = []
    primary = record.coords[0]
    parts.append(f"mapID={primary.map_id}")
    parts.append(f"x={_num(primary.x)}")
    parts.append(f"y={_num(primary.y)}")
    if len(record.coords) > 1:
        coord_parts = []
        for coord in record.coords:
            coord_parts.append(f"{{ {_num(coord.x)}, {_num(coord.y)}, {coord.map_id} }}")
        parts.append("coords={ " + ", ".join(coord_parts) + " }")
    if len(record.qgs) == 1:
        parts.append(f"qg={record.qgs[0]}")
    elif record.qgs:
        parts.append("qgs=" + _lua_int_list(record.qgs))
    if record.source_quests:
        parts.append("sourceQuests=" + _lua_int_list(record.source_quests))
    if record.source_quest_num_required is not None:
        parts.append(f"sourceQuestNumRequired={record.source_quest_num_required}")
    if record.alt_quests:
        parts.append("altQuests=" + _lua_int_list(record.alt_quests))
    if record.faction:
        parts.append(f'faction="{_escape(record.faction)}"')
    if record.races:
        parts.append("races=" + _lua_int_list(record.races))
    if record.classes:
        parts.append("classes=" + _lua_int_list(record.classes))
    if record.min_level is not None:
        parts.append(f"minLevel={record.min_level}")
    if record.max_level is not None:
        parts.append(f"maxLevel={record.max_level}")
    if record.is_breadcrumb:
        parts.append("isBreadcrumb=true")
    if record.repeatable:
        parts.append("repeatable=true")
    if record.is_daily:
        parts.append("isDaily=true")
    if record.is_weekly:
        parts.append("isWeekly=true")
    if record.is_yearly:
        parts.append("isYearly=true")
    if record.is_monthly:
        parts.append("isMonthly=true")
    if record.is_war_effort:
        parts.append("isWarEffort=true")
    if record.is_attunement:
        parts.append("isAttunement=true")
    if record.event is not None:
        parts.append(f"event={int(record.event)}")
    return ", ".join(parts)


def _index_by_map(quests: dict[int, QuestRecord]) -> dict[int, list[int]]:
    by_map: dict[int, list[int]] = {}
    for quest_id in sorted(quests):
        seen: set[int] = set()
        for coord in quests[quest_id].coords:
            if coord.map_id in seen:
                continue
            seen.add(coord.map_id)
            by_map.setdefault(coord.map_id, []).append(quest_id)
    return by_map


def _lua_int_list(values: Iterable[int]) -> str:
    inner = ", ".join(str(int(v)) for v in values)
    return "{ " + inner + " }"


def _num(value: float) -> str:
    if float(value).is_integer():
        return str(int(value))
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return text


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
